import { Theme } from '@/types';

export const THEMES: Theme[] = [
  {
    id: 'arctic-white',
    name: 'Arctic White',
    nameUrdu: 'برفانی سفید',
    gradientFrom: '#ffffff',
    gradientVia: '#f8fafc',
    gradientTo: '#f1f5f9',
    accentColor: '#1e40af',
  },
  {
    id: 'crimson-gold',
    name: 'Crimson Gold',
    nameUrdu: 'سرخ سونا',
    gradientFrom: '#fff5f5',
    gradientVia: '#fff8f0',
    gradientTo: '#fffdf0',
    accentColor: '#c53030',
  },
  {
    id: 'emerald-green',
    name: 'Emerald Green',
    nameUrdu: 'زمرد سبز',
    gradientFrom: '#f0fff4',
    gradientVia: '#f0fffa',
    gradientTo: '#e6fffa',
    accentColor: '#065f46',
  },
  {
    id: 'royal-blue',
    name: 'Royal Blue',
    nameUrdu: 'شاہی نیلا',
    gradientFrom: '#eff6ff',
    gradientVia: '#f0f9ff',
    gradientTo: '#e0f2fe',
    accentColor: '#1d4ed8',
  },
  {
    id: 'ruby-red',
    name: 'Ruby Red',
    nameUrdu: 'یاقوت سرخ',
    gradientFrom: '#fff1f2',
    gradientVia: '#ffe4e6',
    gradientTo: '#fecdd3',
    accentColor: '#be123c',
  },
  {
    id: 'violet-pink',
    name: 'Violet Pink',
    nameUrdu: 'بنفشی گلابی',
    gradientFrom: '#fdf4ff',
    gradientVia: '#fce7f3',
    gradientTo: '#fdf2f8',
    accentColor: '#7c3aed',
  },
  {
    id: 'sapphire',
    name: 'Sapphire',
    nameUrdu: 'نیلم',
    gradientFrom: '#ecfeff',
    gradientVia: '#e0f2fe',
    gradientTo: '#dbeafe',
    accentColor: '#0e7490',
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    nameUrdu: 'گلابی سونا',
    gradientFrom: '#fff7ed',
    gradientVia: '#fef3c7',
    gradientTo: '#fce7f3',
    accentColor: '#c2410c',
  },
  {
    id: 'sunset-orange',
    name: 'Sunset Orange',
    nameUrdu: 'غروب کا نارنجی',
    gradientFrom: '#fff7ed',
    gradientVia: '#ffedd5',
    gradientTo: '#fed7aa',
    accentColor: '#ea580c',
  },
  {
    id: 'crystal-ice',
    name: 'Crystal Ice',
    nameUrdu: 'کرسٹل برف',
    gradientFrom: '#f0fffe',
    gradientVia: '#e0f7fa',
    gradientTo: '#b2ebf2',
    accentColor: '#00838f',
  },
];

export const LANGUAGES = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'ur', name: 'Urdu', native: 'اردو' },
  { code: 'ar', name: 'Arabic', native: 'العربية' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'ru', name: 'Russian', native: 'Русский' },
  { code: 'tr', name: 'Turkish', native: 'Türkçe' },
  { code: 'ps', name: 'Pashto', native: 'پښتو' },
  { code: 'fa', name: 'Persian', native: 'فارسی' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { code: 'zh', name: 'Chinese', native: '中文' },
  { code: 'sd', name: 'Sindhi', native: 'سنڌي' },
  { code: 'bal', name: 'Balochi', native: 'بلوچی' },
];
